# Generated by Django 5.0.6 on 2026-05-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='print_name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='print_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
