# Generated by Django 5.0.6 on 2026-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot_pick',
            field=models.BooleanField(default=False),
        ),
    ]
