# Generated by Django 5.0.6 on 2026-05-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_hot_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquetflower',
            name='max_quantity_per_bouquet',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
