# Generated by Django 5.0.6 on 2026-05-22 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bouquet_flower_max_20'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_method', models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('social_media', 'Social Media'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('order_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_sales', to='products.product')),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
