# Generated by Django 5.0.6 on 2026-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_manual_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualsale',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
