# Generated by Django 5.0.6 on 2026-05-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_print',
            field=models.BooleanField(default=False),
        ),
    ]
