# Generated by Django 5.0.6 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='hot_pick_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jersey',
            name='is_hot_pick',
            field=models.BooleanField(default=False),
        ),
    ]
