from django.core.management.base import BaseCommand

from orders.models import DeliveryLocation

SKIP_NAMES = {'zero', 'test location', 'a', 'out of valley bagbazzar'}

DELIVERY_LOCATIONS = [
    # KATHMANDU - Rs.100
    ("Bagbazaar", "", "Kathmandu", 100),
    ("Kamal Pokhari", "", "Kathmandu", 100),
    ("Battisputali", "", "Kathmandu", 100),
    ("Old Baneshwor", "", "Kathmandu", 100),
    ("Airport Inside Ring Road", "", "Kathmandu", 100),
    ("Sinamangal", "", "Kathmandu", 100),
    ("Tilganga", "", "Kathmandu", 100),
    ("Anamnagar", "", "Kathmandu", 100),
    ("Ghattekulo", "", "Kathmandu", 100),
    ("Singha Durbar", "", "Kathmandu", 100),
    ("Ason", "", "Kathmandu", 100),
    ("Ratnapark", "", "Kathmandu", 100),
    ("Bhrikutimandap", "", "Kathmandu", 100),
    ("Baluwatar", "", "Kathmandu", 100),
    ("Panipokhari", "", "Kathmandu", 100),
    ("New Baneshwor Chowk", "", "Kathmandu", 100),
    ("Bijuli Bazar", "", "Kathmandu", 100),
    ("Shankhamul", "", "Kathmandu", 100),
    ("Buddhanagar", "", "Kathmandu", 100),
    ("Thapagaun Area", "", "Kathmandu", 100),
    ("Ratna Rajya Area", "", "Kathmandu", 100),
    ("Basantapur", "", "Kathmandu", 100),
    ("Sukedhara", "", "Kathmandu", 100),
    ("Chapal Karkhana", "", "Kathmandu", 100),
    ("Dhumbarahi Chowk", "", "Kathmandu", 100),
    ("Chandol", "", "Kathmandu", 100),
    ("Bishalnagar", "", "Kathmandu", 100),
    ("Kalopul", "", "Kathmandu", 100),
    ("Siphal", "", "Kathmandu", 100),
    ("Rato Pool", "", "Kathmandu", 100),
    ("Gaushala", "", "Kathmandu", 100),
    ("Jayabageshwori", "", "Kathmandu", 100),
    ("Hanumandhoka", "", "Kathmandu", 100),
    ("Indrachowk", "", "Kathmandu", 100),
    ("Naradevi", "", "Kathmandu", 100),
    ("Kalimati", "", "Kathmandu", 100),
    ("Bafal", "", "Kathmandu", 100),
    ("Tahachal", "", "Kathmandu", 100),
    ("Soalteemode", "", "Kathmandu", 100),
    ("Kamaladi", "", "Kathmandu", 100),
    ("Ravi Bhawan", "", "Kathmandu", 100),
    ("Lagantole", "", "Kathmandu", 100),
    ("Lazimpat", "", "Kathmandu", 100),
    ("Gairidhara", "", "Kathmandu", 100),
    ("Teaching Hospital", "", "Kathmandu", 100),
    ("Maitidevi", "", "Kathmandu", 100),
    ("Dillibazar Pipalbot", "", "Kathmandu", 100),
    ("Gyaneshwor", "", "Kathmandu", 100),
    ("Tripureshwor", "", "Kathmandu", 100),
    ("Babarmahal", "", "Kathmandu", 100),
    ("Thapathali", "", "Kathmandu", 100),
    ("Maitighar", "", "Kathmandu", 100),
    ("Min Bhawan", "", "Kathmandu", 100),
    ("Shantinagar", "", "Kathmandu", 100),
    ("Bhimsengola", "", "Kathmandu", 100),
    ("Naxal Bhagwati Bahal Area", "", "Kathmandu", 100),
    ("Jamal", "", "Kathmandu", 100),
    ("Naxal Narayan Chour", "", "Kathmandu", 100),
    ("Khusibu", "", "Kathmandu", 100),
    ("Banasthali", "", "Kathmandu", 100),
    ("Newroad", "", "Kathmandu", 100),
    ("Sundhara", "", "Kathmandu", 100),
    ("Putalisadak", "", "Kathmandu", 100),
    ("Kapurdhara", "", "Kathmandu", 100),
    ("Mehpi", "", "Kathmandu", 100),
    ("Ranibari", "", "Kathmandu", 100),
    ("Bhagwan Pau", "", "Kathmandu", 100),
    ("Dallu", "", "Kathmandu", 100),
    ("Chhauni", "", "Kathmandu", 100),
    ("Handigaun", "", "Kathmandu", 100),
    ("Teku", "", "Kathmandu", 100),
    ("Thamel", "", "Kathmandu", 100),
    ("Lainchaur", "", "Kathmandu", 100),
    ("Tinkune", "", "Kathmandu", 100),
    ("Paknajol", "", "Kathmandu", 100),
    ("Dhalko", "", "Kathmandu", 100),
    ("Kantipath", "", "Kathmandu", 100),
    ("Jaishidebal", "", "Kathmandu", 100),
    ("Marutole", "", "Kathmandu", 100),
    ("Ikubahal", "", "Kathmandu", 100),
    ("Tebahal", "", "Kathmandu", 100),
    ("Dharmapath", "", "Kathmandu", 100),
    ("Khichhapokhari", "", "Kathmandu", 100),
    ("Kilagal", "", "Kathmandu", 100),
    ("Tengal", "", "Kathmandu", 100),
    ("Galkhopakha", "", "Kathmandu", 100),
    ("Jyatha", "", "Kathmandu", 100),
    ("Bhotahiti", "", "Kathmandu", 100),
    ("Kamalakshi", "", "Kathmandu", 100),
    ("Bir Hospital", "", "Kathmandu", 100),
    ("Tundikhel", "", "Kathmandu", 100),
    ("Exhibition Road", "", "Kathmandu", 100),
    ("Krishna Pauroti", "", "Kathmandu", 100),
    ("Aloknagar", "", "Kathmandu", 100),
    ("Chhitij Nagar", "", "Kathmandu", 100),
    ("Mahadevsthan", "", "Kathmandu", 100),
    ("Subidhanagar", "", "Kathmandu", 100),
    ("Chun Devi", "", "Kathmandu", 100),
    ("Bhatbhateni", "", "Kathmandu", 100),
    ("Maligaun", "", "Kathmandu", 100),
    ("Sano Gaucharan", "", "Kathmandu", 100),
    ("Tangal", "", "Kathmandu", 100),
    ("Mitrapark", "", "Kathmandu", 100),
    ("Gaurigaun", "", "Kathmandu", 100),
    ("Dhumbarahi Pipalbot", "", "Kathmandu", 100),
    ("Chabahil Chowk", "", "Kathmandu", 100),
    ("Koteshwor Chowk", "", "Kathmandu", 100),
    ("Kalanki Chowk", "", "Kathmandu", 100),
    ("Kuleshwor", "", "Kathmandu", 100),
    ("Balkhu", "", "Kathmandu", 100),
    ("Narayan Gopal Chowk Area", "", "Kathmandu", 100),
    ("Balaju Chowk", "", "Kathmandu", 100),
    ("Balaju Machha Pokhari", "", "Kathmandu", 100),
    ("Sorhakhutte", "", "Kathmandu", 100),
    ("Hattisar", "hattisar", "Kathmandu", 100),
    ("Mahaboudha Ratnapark", "Mahaboudha", "Kathmandu", 100),
    ("Swayambhu Chwok", "", "Kathmandu", 100),
    ("Gangabu Inside", "gangabu", "Kathmandu", 100),
    ("Chamati Bansthali", "chamati", "Kathmandu", 100),
    ("Mid Baneshwor", "", "Kathmandu", 100),
    ("Maharajgunj", "", "Kathmandu", 100),
    ("Nayabazar Sorakhutte", "", "Kathmandu", 100),
    ("Balaju Chauki", "", "Kathmandu", 100),
    ("Gongabu Chowk", "", "Kathmandu", 100),
    ("Samakhusi", "", "Kathmandu", 100),
    ("Mitra Nagar", "", "Kathmandu", 100),
    ("Nayabus Park", "", "Kathmandu", 100),
    # KATHMANDU - Rs.110
    ("Jadibuti Area", "", "Kathmandu", 110),
    ("Balaju Bypass", "", "Kathmandu", 110),
    ("Kumaristhan", "", "Kathmandu", 110),
    ("Sanepa Indrayani Mandir", "", "Lalitpur", 110),
    # KATHMANDU - Rs.120
    ("Narephat", "", "Kathmandu", 120),
    ("Nagarjun Sitapaila Area", "", "Kathmandu", 120),
    ("Nagarjun Thulo Bharyang Area", "", "Kathmandu", 120),
    ("Nagarjun Sano Bharyang Area", "", "Kathmandu", 120),
    ("Nagarjun Soltee Dobato Area", "", "Kathmandu", 120),
    ("Nagarjun Syuchatar", "", "Kathmandu", 120),
    ("Narayangopal Chowk Area", "out side ring raod area", "Kathmandu", 120),
    ("Basundhara Area", "out side ring road area", "Kathmandu", 120),
    ("Chabahil Area", "", "Kathmandu", 120),
    ("Saraswati Nagar Kapan", "saraswotinagar kapan", "Kathmandu", 120),
    ("Gaurighat", "", "Kathmandu", 120),
    ("Gopikrishna Hall Area", "", "Kathmandu", 120),
    ("Chuchepati", "", "Kathmandu", 120),
    ("Kumarigal", "", "Kathmandu", 120),
    ("Pashupathinath", "", "Kathmandu", 120),
    ("Guhyeshwari", "", "Kathmandu", 120),
    ("Domestic Airport", "", "Kathmandu", 120),
    ("Kumari Club", "", "Kathmandu", 120),
    ("International Airport", "", "Kathmandu", 120),
    ("Talchikhel Kusunti", "", "Kathmandu", 120),
    ("Nilopul Sukedhara", "", "Kathmandu", 120),
    ("Boudha Tinchuli", "", "Kathmandu", 120),
    ("Satdobato Outside Area", "", "Kathmandu", 120),
    ("Dhungedhara Area Nagarjun", "dhungedhara", "Kathmandu", 120),
    ("Tokha Gongabu Area", "", "Kathmandu", 120),
    ("Tarakeshwor Dandagaun Area", "", "Kathmandu", 120),
    ("Tarakeshwor Hiledol Area", "", "Kathmandu", 120),
    ("Gangabu Ganeshthan", "gangabu ganeshthan Kathmandu", "Kathmandu", 120),
    ("Kirtipur TU Area", "", "Kathmandu", 120),
    ("Bodhigram Imadole", "", "Lalitpur", 120),
    ("Ekantakuna Outside Ringroad", "ekantakuna", "Lalitpur", 120),
    ("Kusunti Area Lalitpur Outside Ring Road", "", "Lalitpur", 120),
    ("Malpokhari Dhobighat Area", "malpokhari area", "Lalitpur", 130),
    ("Bagdol Area Outside Ring Road", "", "Lalitpur", 120),
    ("Mahalaxmisthan Kusunti", "mahalaxmisthan Kusunti", "Lalitpur", 120),
    ("Hattiban Area", "", "Lalitpur", 120),
    # KATHMANDU - Rs.130
    ("Kalanki Area", "", "Kathmandu", 130),
    ("Satungal Area", "", "Kathmandu", 130),
    ("Pepsicola Area", "", "Kathmandu", 130),
    ("Khadka Gaun Kalanki", "Khadka Gaun Kalanki", "Kathmandu", 130),
    ("Jorpati Chwok", "jorpati oralo, jorpati chowk, boudha to jorapti way", "Kathmandu", 130),
    ("Boudha Area", "", "Kathmandu", 130),
    ("Kapan Area", "kapan area", "Kathmandu", 130),
    ("Bansbari", "", "Kathmandu", 130),
    ("Teenthana Naikap", "teentahna kalanki", "Kathmandu", 130),
    ("Sitapaila Mahankal Area", "Sitapaila Mahankal", "Kathmandu", 130),
    ("Pati Chwok Syuchatar", "Pati Chwok,", "Kathmandu", 130),
    ("Dakshindhoka Area Kageshwori", "Dakshindhoka Area", "Kathmandu", 150),
    ("Gairi Gaun Tindhara Soyambhu", "GAIRI Gaun Tindhara", "Kathmandu", 130),
    ("Nagarjun Tindhara", "", "Kathmandu", 130),
    ("Nagarjun Nursery Chowk", "", "Kathmandu", 130),
    ("Nagarjun Banasthali Kharibot Chowk", "kharibot micro station", "Kathmandu", 130),
    ("Simaltar Kapan", "Simaltar Kapan Kathmandu", "Kathmandu", 140),
    ("Kapan Paiyutar Buspark", "Kapan Paiyutar", "Kathmandu", 150),
    ("Tenzing Chowk Kapan", "tenzing chowk", "Kathmandu", 130),
    ("Chyasindol Area", "chyasindol dhapasi", "Kathmandu", 140),
    ("Imadole ANFA Area Lalitpur", "anfa area", "Lalitpur", 130),
    ("Harisiddhi Lalitpur", "", "Lalitpur", 130),
    ("Khumaltar", "khumaltar area", "Lalitpur", 130),
    ("Nakhipot Area", "", "Lalitpur", 130),
    ("Nakhipot Kantipur Colony", "", "Lalitpur", 130),
    ("Chokhel Area", "", "Lalitpur", 130),
    ("Dholahiti", "", "Lalitpur", 130),
    ("Loha Chowk", "", "Lalitpur", 130),
    ("Ranibu Area", "", "Lalitpur", 130),
    ("Tikathali Mahalaxmi Area", "", "Lalitpur", 130),
    ("Malpokhari Dhobighat Area Lalitpur", "malpokhari area", "Lalitpur", 130),
    ("Nikosera Bhaktapur", "", "Bhaktapur", 140),
    # KATHMANDU - Rs.140
    ("Baluwakhani Kapan", "baluwakhani", "Kathmandu", 130),
    ("Hattigauda Area", "", "Kathmandu", 130),
    ("Gokarneshwar Arubari Area", "", "Kathmandu", 140),
    ("Gokarneshwar Attarkhel Area", "", "Kathmandu", 140),
    ("Gokarneshwar Ramhiti", "", "Kathmandu", 130),
    ("Kageshwori Manohora Gothatar Area", "", "Kathmandu", 140),
    ("Kageshwori Manohora Green Hill City Area", "green hill city jambu dada", "Kathmandu", 140),
    ("Kirtipur Nayabazar Area", "", "Kathmandu", 130),
    ("Kirtipur Buspark Area", "", "Kathmandu", 130),
    ("Kirtipur Panga Area", "panga", "Kathmandu", 140),
    ("Tokha Dhapasi Area", "", "Kathmandu", 130),
    ("Boudha Naya Basti", "nayabasti", "Kathmandu", 140),
    ("Payutar Kapan", "payutar Kapan", "Kathmandu", 140),
    ("Radha Krishnamandir Nagrjun", "Kathmandu", "Kathmandu", 140),
    ("DadaGaun Tarkeshwor", "dadagaun", "Kathmandu", 140),
    ("Jambhu Danda Jorpati", "jambhu danda", "Kathmandu", 140),
    ("Tarakeshwor Manamaiju Area", "", "Kathmandu", 140),
    ("Tarakeshwor Jarankhu Area", "", "Kathmandu", 140),
    ("Tarakeshwor Lolang Area", "", "Kathmandu", 140),
    ("Tarakeshwor Phutung Bus Stop Area", "", "Kathmandu", 140),
    ("Tokha Grande Area", "", "Kathmandu", 140),
    ("Tokha Baniyatar", "", "Kathmandu", 140),
    ("Gokarneshwar Arubari", "", "Kathmandu", 140),
    ("Kageshwori Manohara Gothatar Tej Binayak Chowk", "", "Kathmandu", 140),
    ("Kadaghari Birendra Chowk", "", "Kathmandu", 140),
    ("Budhanilkantha Nayapul", "", "Kathmandu", 140),
    ("Nayapul Jorpati", "Nayapul", "Kathmandu", 140),
    ("Bhangal Kapan", "Bhangal", "Kathmandu", 150),
    ("Bhatkepati Area Kritipur", "Bhatkepati area - Kritipur", "Kathmandu", 150),
    ("Dhapakhel Dobato Lalitpur", "dapakhel", "Lalitpur", 140),
    ("Dhapakhel Buspark Lalitpur", "dapakhel", "Lalitpur", 140),
    ("Nagdaha Dhapakhel Lalitpur", "", "Lalitpur", 140),
    ("Ochu Height Imadole Lalitpur", "ochu height", "Lalitpur", 140),
    ("Shital Height Imadole Lalitpur", "shital height", "Lalitpur", 140),
    ("Sidhipur Imadole Lalitpur", "sidhhapur buspark", "Lalitpur", 150),
    ("Nakhudol Area Lalitpur", "nakhudol area", "Lalitpur", 140),
    ("Sanogaun Imadole Area Lalitpur", "", "Lalitpur", 140),
    ("Sunakoti Area Lalitpur", "", "Lalitpur", 140),
    ("Bhaisepati Area Lalitpur", "", "Lalitpur", 140),
    ("Dhapakhel Area Lalitpur", "", "Lalitpur", 130),
    ("Nakhu Area Lalitpur", "", "Lalitpur", 130),
    ("Imadole Area Lalitpur", "", "Lalitpur", 130),
    ("Thaiba Godawari Lalitpur", "", "Lalitpur", 140),
    ("Thecho Godawari Lalitpur", "", "Lalitpur", 140),
    ("Khokana Karyabinayak Lalitpur", "", "Lalitpur", 140),
    ("Muktinath Temple Area Lalitpur", "karki tar, damaitar, bajrayogini temple, mulpani youth club", "Lalitpur", 160),
    ("Nagdaha Dhapakhel", "", "Lalitpur", 140),
    ("Maitrinagar Kritipur Kathmandu", "ashirbad chwok, hospital road", "Kathmandu", 140),
    ("Duwakot Mode Bhaktapur", "", "Bhaktapur", 140),
    ("Tokha Jalpachowk", "", "Kathmandu", 130),
    ("Lolang Boharatar", "lolang", "Kathmandu", 140),
    ("Nagarjun Padma Colony", "", "Kathmandu", 140),
    ("Sitapaila Mahankal Kathmandu", "Sitapaila Mahankal", "Kathmandu", 130),
    # KATHMANDU - Rs.150
    ("Budhanilkantha Narayanthan Temple Area", "", "Kathmandu", 150),
    ("Budhanilkantha Golfutar Area", "", "Kathmandu", 130),
    ("Budhanilkantha Mandikhatar Area", "", "Kathmandu", 130),
    ("NaagPokhari Tarkeshwor", "nagpokhari area", "Kathmandu", 150),
    ("Pasikot Budanilkantha", "pasikot Budanilkantha", "Kathmandu", 150),
    ("Thulo Bharyang Height Area", "nagarjun", "Kathmandu", 150),
    ("Basnettar Tarkeshwor", "Basnettar, Tarkeshwor Kathmandu", "Kathmandu", 150),
    ("Airport Domestic Drop", "air cargo", "Kathmandu", 150),
    ("Dhalmal Pool Area Tarkeshwor", "dhalmal pool", "Kathmandu", 150),
    ("Suntakhan Gokarna", "suntakhan", "Kathmandu", 200),
    ("Paiyatar Tarkeshwor", "paiyatar area", "Kathmandu", 150),
    ("Hepali Height Budhanilkantha", "hepali height", "Kathmandu", 140),
    ("Kapan Gumba", "kapan gumba", "Kathmandu", 150),
    ("Nagarjun Raniban Area", "", "Kathmandu", 150),
    ("Tokha Suryadarshan Height", "", "Kathmandu", 150),
    ("Tokha Bhatke Ko Pool", "bhatkeko pull / dhalmal pulla", "Kathmandu", 150),
    ("Tokha Tokha Ganeshthan Area", "", "Kathmandu", 150),
    ("Goldhunga Area Tarakeshwor", "", "Kathmandu", 150),
    ("Tarakeshwor Dharmasthali", "dharmasthali", "Kathmandu", 150),
    ("Budhanilkantha Paiyatar Area", "", "Kathmandu", 150),
    ("Karuna Hospital Area Kapan", "Karuna hospital area", "Kathmandu", 150),
    ("Swayambhu Kathmandu", "soyambhu", "Kathmandu", 100),
    ("Swayambhu Outside Ring Road", "soyambhu", "Kathmandu", 120),
    ("School Chwok Area Lubhu Lalitpur", "school chwok lubhu", "Lalitpur", 150),
    ("Lubhu Mahalaxmi Area Lalitpur", "lubhu", "Lalitpur", 150),
    ("Changathali Mahalaxmi Area Lalitpur", "", "Lalitpur", 150),
    ("Dungin Mahalaxmi Area Lalitpur", "", "Lalitpur", 150),
    ("Chapagaun Buspark Area Godawari Lalitpur", "chapagaun", "Lalitpur", 150),
    ("Jharuwarasi Godawari Lalitpur", "", "Lalitpur", 150),
    ("Toukhel Area Godawari Lalitpur", "", "Lalitpur", 150),
    ("Dhaichhap Karyabinayak Lalitpur", "", "Lalitpur", 150),
    ("BadeGaun Godwari Lalitpur", "badegaun", "Lalitpur", 150),
    ("Durbar Square Area Bhaktapur", "", "Bhaktapur", 150),
    ("Dadhikot Area Bhaktapur", "", "Bhaktapur", 150),
    ("Saraswotikhel Bhaktapur", "sawaswotikhel", "Bhaktapur", 150),
    ("Sirutar Bhaktapur", "", "Bhaktapur", 150),
    ("Byasi Area Bhaktapur", "", "Bhaktapur", 150),
    ("Tokha Bhutkhel", "", "Kathmandu", 150),
    ("Kageshwori Manohara Mulpani Lalitpur", "", "Kathmandu", 150),
    ("Budhanilkantha Nayapul Kathmandu", "", "Kathmandu", 140),
    ("Tarakeshwor Kavresthali Buspark Area", "", "Kathmandu", 175),
    ("Bishnudevi Temple Kirtipur", "Bishnudevi Temple", "Kathmandu", 150),
    ("Barmakhel Bus Station Sankhu", "barmakhel bus stop", "Kathmandu", 180),
    ("Dakshindhoka Area Kageshwori Kathmandu", "Dakshindhoka Area", "Kathmandu", 150),
    ("Nagarjun Panchdhara Area", "panchdhara", "Kathmandu", 140),
    # KATHMANDU - Rs.160+
    ("Budhanilkantha Chapali Area", "", "Kathmandu", 160),
    ("Kirtipur Chovar", "chovar pani tyanki, chovar dry port, chovar height", "Kathmandu", 160),
    ("Gokarneshwar Nayapati", "", "Kathmandu", 160),
    ("Gokarneshwar Temple Area", "", "Kathmandu", 150),
    ("Kageshwori Manohora Mulpani Chaur", "", "Kathmandu", 175),
    ("Kageshwori Manohara Thali", "", "Kathmandu", 160),
    ("Kageshwori Manohara Mulpani", "", "Kathmandu", 150),
    ("Kirtipur Taudaha", "taudha area", "Kathmandu", 200),
    ("Macchegaun Kathmandu", "", "Kathmandu", 175),
    ("Nagdhunga", "nagdhunga area", "Kathmandu", 200),
    ("Pharping Kathmandu", "Pharping", "Kathmandu", 200),
    ("Thankot Area Kathmandu", "", "Kathmandu", 160),
    ("Chalnakhel Kathmandu", "chalnakhel delivery area delievry root milyera matra huncha ewooo", "Kathmandu", 200),
    ("Check Post Area Thankot", "", "Kathmandu", 150),
    ("Taulung Chautara Area Budhanilkantha", "naranthan taulung chautra and nilo pool area", "Kathmandu", 175),
    ("Ichangu Temple Area", "ichangu", "Kathmandu", 175),
    ("Matatirtha Gairi Gaun Chandragiri", "matatirtha height", "Kathmandu", 175),
    ("Gamcha Chwok Bhaktapur", "", "Bhaktapur", 160),
    ("Tokha Chandeshwori Area", "Tokha Chandeshwori Area Kathmandu", "Kathmandu", 165),
    ("Danchhi Kageshwori", "danchhi", "Kathmandu", 170),
    ("Machchhegaun Kirtipur", "kritipur", "Kathmandu", 180),
    ("Shankharapur Sankhu", "", "Kathmandu", 200),
    ("Sundarijal", "", "Kathmandu", 200),
    ("Simachaur Jhoor Tokha", "Simachaur chwok", "Kathmandu", 200),
    ("Bhimdhunga Nagarjun Area", "", "Kathmandu", 200),
    ("Sangla Balkumari School Area", "sangla balkumari school", "Kathmandu", 200),
    ("Jitpurfedi Last Stop Tarkeshwor", "jitpurfedi last stop tarkeshwor", "Kathmandu", 200),
    ("Sangla Tarakeshwor", "sangla", "Kathmandu", 160),
    ("Nagarjun White Gumba", "whitegumba", "Kathmandu", 175),
    ("Nagarjun Ramkot Area", "ramkot area", "Kathmandu", 175),
    ("Gamcha Budanilkantha", "", "Kathmandu", 175),
    ("Jagdol Area Budhanilkantha", "", "Kathmandu", 150),
    ("Deuba Chowk Budanilkantha", "deuba chowk area", "Kathmandu", 150),
    ("Chandragiri Cable Car Station", "", "Kathmandu", 150),
    ("Matatirtha Area", "", "Kathmandu", 150),
    ("Bishnumati Pull Narayanthan", "bishnumati pull", "Kathmandu", 170),
    ("Single Tree Kathmandu", "", "Kathmandu", 160),
    ("Futung Area Kathmandu", "", "Kathmandu", 140),
    ("Gurjudhara Yatayat Kathmandu", "gurjudhara yatayat", "Kathmandu", 140),
    ("Nagarjun Naya Naikap", "", "Kathmandu", 130),
    ("Nagarjun Purano Naikap Area", "", "Kathmandu", 140),
    ("Kirtipur Tyanglaphat Area", "", "Kathmandu", 140),
    ("Balaju Height Boharatar", "balaju height, boharatar", "Kathmandu", 140),
    ("Shankharapur Salambutar", "", "Kathmandu", 175),
    ("Purano Gueshwari Area", "", "Kathmandu", 130),
    ("Sano Bypass Chisapani", "", "Kathmandu", 150),
    ("Gangahiti", "", "Kathmandu", 120),
    ("Narayantar Kageshwori Manohara", "", "Kathmandu", 140),
    ("Dadapuwa Ramkot", "dadapauwa area", "Kathmandu", 160),
    ("Budhanilkantha Chunikhel Buspark Area", "Thane hiti, chunikhel buspark, bunga park", "Kathmandu", 160),
    ("Tokha Tokha Jalpachowk", "", "Kathmandu", 130),
    ("Kapan Kharibot", "kapan kharibot", "Kathmandu", 140),
    ("Chisapani Area Sano ByPass", "chisapani area", "Kathmandu", 175),
    ("Mahankal Kapan Kathmandu", "mahankal kapan", "Kathmandu", 130),
    ("Nagarkot", "", "Kavrepalanchowk", 225),
    ("Tinpiple Chisapani Trakeshwor", "same day may not possible", "Kathmandu", 250),
    # LALITPUR - Inside Ring Road Rs.100
    ("Satdobato Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Gwarko Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Jawalakhel Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Kupandol Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Lagankhel Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Jhamsikhel Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Mangalbazar Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Kumaripati Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Sanepa Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Patandhoka Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Pulchowk Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Chakupat Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Kusunti Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Banglamukhi Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Balkumari Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Kalopul Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Patan Hospital Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Thaina Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Macchindrabahal Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Kanibahal Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Sundhara Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Guitole Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Chayasal Area Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Thasikhel Lalitpur Inside Ring Road", "", "Lalitpur", 100),
    ("Chyasal Lalitpur", "", "Lalitpur", 100),
    ("Dhobighat Inside Ring Road Lalitpur", "", "Lalitpur", 100),
    ("Bakhundol Lalitpur", "", "Lalitpur", 100),
    # LALITPUR - Rs.175-250
    ("Takhel Area Chapagaun Lalitpur", "Takhel Area,", "Lalitpur", 185),
    ("Godamchaur Godawari Lalitpur", "godamchaur", "Lalitpur", 160),
    ("Badikhel Godwari Lalitpur", "badikhel", "Lalitpur", 175),
    ("Godawari Bajrabarahi Area Lalitpur", "", "Lalitpur", 175),
    ("Chhampi Karyabinayak Lalitpur", "", "Lalitpur", 175),
    ("Chunikhel Karyabinayak Lalitpur", "", "Lalitpur", 170),
    ("Bungamati Area Lalitpur", "", "Lalitpur", 175),
    ("Botanical Garden Area Godawari Lalitpur", "", "Lalitpur", 200),
    ("Tikabhairabh Karyabinayak Lalitpur", "", "Lalitpur", 250),
    ("Sunrise Tower Dhobighat Lalitpur", "sunrise tower", "Lalitpur", 120),
    ("Maitrinagar Kalanki Kathmandu", "", "Kathmandu", 120),
    # BHAKTAPUR
    ("Suryabinayak Area Bhaktapur", "", "Bhaktapur", 150),
    ("Gaththaghar Area Bhaktapur", "", "Bhaktapur", 130),
    ("Lohakanthali Area Bhaktapur", "", "Bhaktapur", 120),
    ("New Thimi Bhaktapur", "", "Bhaktapur", 130),
    ("Balkot Area Bhaktapur", "", "Bhaktapur", 130),
    ("Kamalbinayak Area Bhaktapur", "kamal binyak", "Bhaktapur", 175),
    ("Kausaltar Area Bhaktapur", "", "Bhaktapur", 120),
    ("Sallaghari Area Bhaktapur", "", "Bhaktapur", 140),
    ("Old Thimi Bhaktapur", "", "Bhaktapur", 130),
    ("Jagati Area Bhaktapur", "", "Bhaktapur", 160),
    ("Sano Thimi Area Bhaktapur", "", "Bhaktapur", 130),
    ("Duwakot Area Bhaktapur", "", "Bhaktapur", 160),
    ("Chyamasing Area Bhaktapur", "", "Bhaktapur", 170),
    ("Palanse Bhaktapur", "", "Bhaktapur", 250),
    ("Bode Bhaktapur", "", "Bhaktapur", 140),
    ("Katunje Area Bhaktapur", "katuneje", "Bhaktapur", 150),
    ("Nepal Military Academy Bhaktapur", "", "Bhaktapur", 180),
    ("Biruwa Buspark Area Bhaktapur", "", "Bhaktapur", 200),
    ("SUDAL Bhaktapur", "", "Bhaktapur", 200),
    ("Lokanthali Bhaktapur", "lokanthali area", "Bhaktapur", 130),
    ("Changunarayan Bhaktapur", "", "Bhaktapur", 175),
    ("Radhe Radhe Bhaktapur", "", "Bhaktapur", 140),
    ("Srijananagar Bhaktapur", "", "Bhaktapur", 140),
    ("Dekocha Area Bhaktapur", "", "Bhaktapur", 160),
    ("Dekocha Bhaktapur", "", "Bhaktapur", 175),
    ("Jhaukhel Bhaktapur", "jhaukhel area", "Bhaktapur", 175),
    ("Mahankal Changu Bhaktapur", "mahankal changunarayan area", "Bhaktapur", 175),
    ("Military Academy Kharipati Bhaktapur", "", "Bhaktapur", 175),
    ("Ratopati Bhaktapur", "", "Bhaktapur", 175),
    ("Nepal Engineering College Bhaktapur", "", "Bhaktapur", 175),
    ("Sipadaol Area Bhaktapur", "sipadole area", "Bhaktapur", 175),
    ("Gundu Bhaktapur", "", "Bhaktapur", 175),
    ("Dibyashwori Planning Pepsicola Bhaktapur", "", "Bhaktapur", 140),
    ("Thathali Bhaktapur", "", "Bhaktapur", 200),
    ("Doleshwor Bhaktapur", "", "Bhaktapur", 200),
    ("Siddhapokhari Bhaktapur", "", "Bhaktapur", 150),
    ("Kharipati Area Bhaktapur", "karipati buspak nagarkot raod", "Bhaktapur", 200),
    # OUTSIDE VALLEY - Pokhara / Kaski
    ("Pokhara", "", "Kaski", 200),
    ("Lekhnath", "", "Kaski", 225),
    ("Hemja Kaski", "", "Kaski", 250),
    ("Naudanda Kaski", "", "Kaski", 250),
    ("Phedikhola Syangja DHN", "phedikhola", "Syangja", 325),
    # Chitwan
    ("Bharatpur Chitwan", "chitwan", "Chitwan", 200),
    ("Tandi Chitwan", "", "Chitwan", 225),
    ("Narayangarh Chitwan", "", "Chitwan", 200),
    ("Bhandara Chitwan", "", "Chitwan", 275),
    ("Parsa Chitwan", "", "Chitwan", 250),
    ("Mugling Chitwan", "SHYAULI BAZAR, KHAHARE KHONA, 1.NO PUL, KURINTAR", "Chitwan", 275),
    ("Madi Chitwan", "", "Chitwan", 275),
    ("Padampur Chitwan", "", "Chitwan", 250),
    ("Lothar Chitwan", "", "Chitwan", 275),
    ("Meghauli Chitwan", "", "Chitwan", 275),
    ("Jugedi Chitwan", "", "Chitwan", 225),
    ("Jagatpur Chitwan", "DEVNAGAR, CHAMPA NAGAR, UJELI NAGAR, GANGA NAGAR, SHITAMAI, BARAUJI, SUNDAR BASTI, PAKAUDI, PADAMPOKHARI, PATENI, JAGATPURCHOWK, PARTITUR, KRISHNA CHOWK, 7NO. CHOWK, JIMMAL CHOWK, KASARA, GAILAGHARI, KESARBARG", "Chitwan", 275),
    ("Sauraha Chitwan", "", "Chitwan", 250),
    ("Khurkhure Chitwan", "", "Chitwan", 250),
    # Rupandehi
    ("Butwal Rupandehi", "", "Rupandehi", 200),
    ("Bhairahawa Rupandehi", "", "Rupandehi", 200),
    ("Manigram Rupandehi", "", "Rupandehi", 225),
    ("Manigram Tilottama Rupandehi", "", "Rupandehi", 225),
    ("Bhalwari Rupandehi", "", "Rupandehi", 250),
    ("Jogikuti Rupandehi", "", "Rupandehi", 225),
    ("Lumbini Bazar Rupandehi", "", "Rupandehi", 250),
    ("Kanchi Bazar Rupandehi", "", "Rupandehi", 275),
    ("Amuwa Rupandehi", "", "Rupandehi", 275),
    ("Khaireni Rupandehi", "", "Rupandehi", 275),
    ("Pharsatikar Rupandehi", "", "Rupandehi", 275),
    ("Kotihawa Rupandehi", "", "Rupandehi", 250),
    ("Motipur Rupandehi", "", "Rupandehi", 275),
    ("Tamnagar Rupandehi", "", "Rupandehi", 250),
    ("Rudrapur Haraiya Rupandehi", "", "Rupandehi", 275),
    # Kapilbastu
    ("Taulihawa Kapilbastu", "", "Kapilbastu", 250),
    ("4 No Jeetpur Kapilbastu", "", "Kapilbastu", 250),
    ("Gorusinge Kapilbastu", "", "Kapilbastu", 250),
    ("Chandrauta Kapilbastu", "", "Kapilbastu", 250),
    ("Imiliya Kapilbastu", "", "Kapilbastu", 275),
    # Palpa / Syangja / Argha
    ("Tansen Palpa", "", "Palpa", 225),
    ("Rampur Palpa", "", "Palpa", 250),
    ("Syangja Galyang", "", "Syangja", 250),
    ("Syangja Putalibazar", "", "Syangja", 250),
    ("Syangja Waling", "", "Syangja", 225),
    ("Bayarghari Syangja", "", "Syangja", 275),
    ("Sandhikharka Arghakhanchi", "", "Arghakhanchi", 250),
    # Gulmi / Myagdi / Parbat / Baglung / Mustang / Manang
    ("Tamghas Gulmi", "", "Gulmi", 250),
    ("Ridi Gulmi", "", "Gulmi", 275),
    ("Shantipur Gulmi", "", "Gulmi", 300),
    ("Baletaxar Gulmi", "", "Gulmi", 275),
    ("Wamitaksar Gulmi", "", "Gulmi", 300),
    ("Beni Myagdi", "", "Myagdi", 225),
    ("Darwang Myagdi", "THAPA CHAUR, TALLO BAZAR, BUDDHA SANTI TOL, HULAK TOL, DHAULAGIRI TOL, NAYA BAZAR, JANA PRIYA BIKASH TOL, SHANTI TOL, KB BOARDING AREA, MATHILLO BAZAR", "Myagdi", 325),
    ("Kusma Parbat", "", "Parbat", 250),
    ("Galkot Baglung", "", "Baglung", 250),
    ("Burtibang Baglung", "", "Baglung", 275),
    ("Baglung Baglung", "", "Baglung", 225),
    ("Jomsom Mustang", "", "Mustang", 325),
    ("Chame Manang", "", "Manang", 325),
    # Lamjung / Tanahun / Gorkha
    ("Besi Sahar Lamjung", "", "Lamjung", 275),
    ("Duipiple Lamjung", "DUIPIPLE BAZAR AREA, RAM BAZAR, SISAGHAT, POLANG, SATRASAYA, SOTIPASAL, OAKHURI CHOWK, BHORLETAR", "Lamjung", 300),
    ("Sundar Bazar Lamjung", "", "Lamjung", 275),
    ("Damauli Tanahun", "", "Tanahun", 225),
    ("Dumre Tanahun", "", "Tanahun", 225),
    ("Bhimad Tanahun", "BHIMAD BAZAR, CHHANGPATAN, RISHINPATAN, BATTAR, SISNERI, MISURLUNG, LALYIN BAZAR, MALEBAGAR, CAMPUS ROAD, RAANGRUNG, GILANG", "Tanahun", 300),
    ("Aanbu Khaireni Tanahun", "", "Tanahun", 275),
    ("Dulegaunda Tanahun", "", "Tanahun", 275),
    ("Bandipur Tanahun", "", "Tanahun", 300),
    ("Gorkha Bazar", "", "Gorkha", 250),
    ("Palungtar Gorkha", "", "Gorkha", 275),
    # Dang / Pyuthan / Rolpa / Salyan
    ("Lamahi Dang", "", "Dang", 250),
    ("Tulsipur Dang", "", "Dang", 225),
    ("Ghorahi Dang", "", "Dang", 225),
    ("Narayanpur Dang", "", "Dang", 275),
    ("Gogali Dang", "", "Dang", 275),
    ("Bhalubang Dang", "", "Dang", 250),
    ("Mourighat Dang", "", "Dang", 250),
    ("Pyuthan", "BIJUWAR, BAGDULA, JUMRI BUSPARK, RATAMATA, DAKHAQUADY, CHERNETA, PUHDYAKHOLA, TIKURI, BIZUWAR TARI, BIJAYANAGAR", "Pyuthan", 275),
    ("Bhingri Pyuthan", "", "Pyuthan", 300),
    ("Pyuthan Khalanga", "", "Pyuthan", 300),
    ("Liwang Rolpa", "", "Rolpa", 275),
    ("Sulichaur Rolpa", "", "Rolpa", 275),
    ("Salyan Khalanga", "", "Salyan", 250),
    ("Shreenagar Salyan", "", "Salyan", 275),
    ("Tharmare Salyan", "", "Salyan", 250),
    # Kailali / Kanchanpur / Bardiya / Banke / Surkhet
    ("Dhangadi Kailali", "", "Kailali", 225),
    ("Tikapur Kailali", "", "Kailali", 250),
    ("Lamki Kailali", "", "Kailali", 250),
    ("Sukkhad Kailali", "", "Kailali", 250),
    ("Bhajani Kailali", "", "Kailali", 250),
    ("Chaumala Kailali", "", "Kailali", 275),
    ("Pahalbanpur Kailali", "", "Kailali", 250),
    ("Joshipur Kailali", "", "Kailali", 275),
    ("Bauniya Kailali", "", "Kailali", 250),
    ("Masuriya Kailali", "", "Kailali", 275),
    ("Chisapani Kailali", "", "Kailali", 250),
    ("Attariya Kailali", "", "Kailali", 225),
    ("Beldandi Kanchanpur", "", "Kanchanpur", 275),
    ("Jhalari Kanchanpur", "", "Kanchanpur", 275),
    ("Dodhara Chandani Kanchanpur", "", "Kanchanpur", 275),
    ("Punarbas Kanchanpur", "", "Kanchanpur", 275),
    ("Gulariya Kanchanpur", "", "Kanchanpur", 275),
    ("Belauri Kanchanpur", "", "Kanchanpur", 275),
    ("Mahendranagar Kanchanpur", "", "Kanchanpur", 250),
    ("Kohalpur Banke", "", "Banke", 225),
    ("Nepalgunj Banke", "", "Banke", 225),
    ("Khajura Banke", "", "Banke", 275),
    ("Samshergunj Banke", "", "Banke", 300),
    ("Piprahawa Banke", "", "Banke", 250),
    ("Gulariya Bardiya", "", "Bardiya", 250),
    ("Bhurigoan Bardiya", "", "Bardiya", 250),
    ("Rajapur Bardiya", "", "Bardiya", 250),
    ("Bansagadhi Bardiya", "", "Bardiya", 275),
    ("Taratal Bardiya", "", "Bardiya", 275),
    ("Jayanagar Bardiya", "", "Bardiya", 275),
    ("Surkhet", "", "Surkhet", 250),
    ("Mehelkuna Surkhet", "", "Surkhet", 300),
    ("Chinchu Surkhet", "", "Surkhet", 250),
    # Dailekh / Jajarkot / Kalikot / Rukum / Salyan / Achham / Doti / Dadeldhura / Bajhang / Bajura / Baitadi / Humla / Mugu / Dolpa
    ("Dailekh Bazar", "", "Dailekh", 275),
    ("Dullu Dailekh", "", "Dailekh", 325),
    ("Jajarkot Khalanga", "", "Jajarkot", 325),
    ("Manma Kalikot", "", "Kalikot", 325),
    ("Musikot Rukum W", "", "Rukum West", 300),
    ("Rukumkot Rukum E", "", "Rukum East", 325),
    ("Rukum Chaurjahari", "", "Rukum West", 325),
    ("Mangalsen Achham", "", "Achham", 350),
    ("Sanfebagar Achham", "", "Achham", 320),
    ("Kamal Bazar Achham", "home delivery may not possible", "Achham", 325),
    ("Dipayal Bazar Doti", "", "Doti", 300),
    ("Silgadhi Doti", "", "Doti", 300),
    ("Amargadhi Dadeldhura", "", "Dadeldhura", 300),
    ("Chainpur Bajhang", "", "Bajhang", 325),
    ("Martadi Bajura", "", "Bajura", 325),
    ("Kolti Bajura", "", "Bajura", 325),
    ("Gothalapani Baitadi", "", "Baitadi", 325),
    ("Patan Baitadi", "", "Baitadi", 325),
    ("Simikot Humla", "", "Humla", 325),
    ("Gamgadhi Mugu", "", "Mugu", 325),
    ("Dunai Dolpa", "", "Dolpa", 325),
    ("Jumla Khalanga", "", "Jumla", 325),
    ("Darchula Khalanga", "", "Darchula", 325),
    ("Gokuleshwor Darchula", "", "Darchula", 325),
    # Nawalparasi / Parsa / Bara / Rautahat / Sarlahi / Mahottari / Dhanusha / Siraha / Saptari
    ("Bardaghat Nawalparasi W", "", "Nawalparasi West", 225),
    ("Parasi Nawalparasi W", "", "Nawalparasi West", 250),
    ("Sunwal Nawalparasi W", "", "Nawalparasi West", 225),
    ("Dumkibas Nawalparasi E", "", "Nawalparasi East", 225),
    ("Daldale Nawalparasi E", "", "Nawalparasi East", 225),
    ("Gaidakot Nawalparasi E", "", "Nawalparasi East", 225),
    ("Arunkhola Nawalparasi E", "", "Nawalparasi East", 250),
    ("Chormara Nawalparasi E", "", "Nawalparasi East", 225),
    ("Harkapur 16 No Nawalparasi E", "", "Nawalparasi East", 275),
    ("Rajahar Nawalparasi", "CG Temple", "Nawalparasi East", 250),
    ("Birgunj Parsa", "", "Parsa", 225),
    ("Pokhariya Parsa", "", "Parsa", 275),
    ("Simara Bara", "", "Bara", 250),
    ("Pathlaiya Bara", "", "Bara", 250),
    ("Kolhabi Bazar Bara", "", "Bara", 300),
    ("Jeetpur Bara", "", "Bara", 250),
    ("Piluwa Bara", "", "Bara", 275),
    ("Nijgadh Bara", "", "Bara", 250),
    ("Kalaiya Bara", "", "Bara", 250),
    ("Gaur Rautahat", "", "Rautahat", 250),
    ("Chandranigahapur Rautahat", "SANTAPUR, BASANTAPUR, DUMARIYA, BALCHANPUR, MOTHIYAHI, ALTOKI, SINDURIGHARI, GAIRATAR, MILAN CHOWK, CHANDRANIGAHAPUR BAZZAR, DEURALI CHOWK, CHIRIYADHA CHOWK, TEKAN TOL, BUDDHA CHOWK, THALAI TOL, JHANJHAN TOL, BELDI, SUNDAR BASTI, MOTIPUR, ARMY BARRACK, CHETNAGAR BIRTA, JUDIBELA, Chapur", "Rautahat", 250),
    ("Garuda Rautahat", "", "Rautahat", 300),
    ("Hariwan Sarlahi", "NAYAROAD, SUKEPOKHARI, DHARAHARA, PUTALICHOWK, KAMAIYA, BAGMATI, MILANCHOWK, GANESHCHOWK, DABARI, PURANO BAZAR, CHAPAINI, GHURKAULI, JAGATPUR, TRITAGAAXI, BATHANE, LAXMIPUR", "Sarlahi", 250),
    ("Malangwa Sarlahi", "", "Sarlahi", 250),
    ("Barahathawa Sarlahi", "", "Sarlahi", 275),
    ("Haripur Sarlahi", "HARIPUR BAZAR, JUTPANI, NAWALPUR", "Sarlahi", 250),
    ("Lahan Siraha", "", "Siraha", 225),
    ("Golbazar Siraha", "", "Siraha", 250),
    ("Sukhipur Siraha", "", "Siraha", 250),
    ("Dhangadhimai Siraha", "", "Siraha", 250),
    ("Mirchaiya Siraha", "", "Siraha", 250),
    ("Siraha Bazar Siraha", "", "Siraha", 275),
    ("Janakpur Dhanusha", "", "Dhanusha", 225),
    ("Mahendranagar Dhanusa", "", "Dhanusha", 250),
    ("Birendra Bazar Dhanusha", "", "Dhanusha", 250),
    ("Nagarain Dhanusha", "", "Dhanusha", 250),
    ("Dhanusadham Dhanusha", "", "Dhanusha", 250),
    ("Sabaila Dhanusha", "", "Dhanusha", 300),
    ("Dhalkebar Dhanusha", "", "Dhanusha", 225),
    ("Rajbiraj Saptari", "", "Saptari", 225),
    ("Kanchanpur Saptari", "", "Saptari", 250),
    ("Phattepur Saptari", "", "Saptari", 275),
    ("Kalyanpur Saptari", "", "Saptari", 275),
    ("Rupani Saptari", "", "Saptari", 250),
    ("Tuteshwar Mahottari", "", "Mahottari", 275),
    ("Gaushala Mahottari", "", "Mahottari", 250),
    ("Jaleshwor Mahottari", "", "Mahottari", 250),
    ("Sindhuli Bazzar", "", "Sindhuli", 225),
    ("Dudhauli Sindhuli", "", "Sindhuli", 250),
    ("Bhiman Sindhuli", "", "Sindhuli", 275),
    ("Khurkot Sindhuli", "", "Sindhuli", 275),
    # Morang / Sunsari / Jhapa / Ilam / Panchthar / Terhathum / Taplejung / Sankhuwasabha / Bhojpur / Khotang / Okhaldhunga / Solukhumbu
    ("Biratchowk Morang", "", "Morang", 225),
    ("Pathari Morang", "", "Morang", 250),
    ("Letang Morang", "", "Morang", 275),
    ("Madhumalla Morang", "", "Morang", 250),
    ("Kerabari Morang", "", "Morang", 275),
    ("Rangeli Morang", "", "Morang", 225),
    ("Belbari Morang", "", "Morang", 225),
    ("Uralabari Morang", "", "Morang", 225),
    ("Sombare Morang", "", "Morang", 275),
    ("Neta Chowk Morang", "", "Morang", 250),
    ("Bansbari Morang", "", "Morang", 225),
    ("Tanki Morang", "NIMUWA, TANKI, BANSBARI, BIRAT TEACHING HOSPITAL, GANGA CHOWK, MANMOHAN CHOWK, GUKUWA", "Morang", 200),
    ("Itahari Sunsari", "", "Sunsari", 200),
    ("Inaruwa Sunsari", "", "Sunsari", 225),
    ("Duhabi Sunsari", "", "Sunsari", 225),
    ("Chatara Sunsari", "", "Sunsari", 250),
    ("Jhumka Sunsari", "", "Sunsari", 225),
    ("Kalabanjar Sunsari", "", "Sunsari", 250),
    ("Tarahara Sunsari", "", "Sunsari", 225),
    ("Chakarghatti Sunsari", "BANGE, SOMBARE CHOWK, SUKBARE CHOWK, AAITABARE RANGA CHOWK, MUNAL CHOWK BUDHABARE CHOWK, MAHENDRAGET, BISNUCHOCK SALABANDI, SHERE CHOCK", "Sunsari", 250),
    ("Bhantabari Sunsari", "KOSHI BRIDGE, KOSHI KATAN, KOSHI TAPU, HARIPUR, SHIRPUR, MADHUBAN", "Sunsari", 275),
    ("Bhedetar Sunsari", "", "Sunsari", 300),
    ("Prakashpur Sunsari", "", "Sunsari", 250),
    ("Gauriganj Jhapa", "", "Jhapa", 250),
    ("Birtamod Jhapa", "", "Jhapa", 225),
    ("Kakarbhitta Jhapa", "", "Jhapa", 250),
    ("Dhulabari Jhapa", "", "Jhapa", 250),
    ("Haldibari Jhapa", "SHAMBHU CHOWK, PARAKHOPI, MANGALBARE, ADHIKARI CHOWK, TADUWA, MAJORNI CHOWK (1-2 days)", "Jhapa", 250),
    ("Bhadrapur Jhapa", "", "Jhapa", 225),
    ("Budhabare Jhapa", "", "Jhapa", 250),
    ("Rajgadh Jhapa", "", "Jhapa", 250),
    ("Laxmipur Jhapa", "", "Jhapa", 250),
    ("Sanischare Jhapa", "", "Jhapa", 250),
    ("Gauradaha Jhapa", "", "Jhapa", 250),
    ("Surunga Jhapa", "", "Jhapa", 250),
    ("Kerkha Jhapa", "", "Jhapa", 250),
    ("Bahundangi Jhapa", "", "Jhapa", 250),
    ("Goldhap Jhapa", "", "Jhapa", 250),
    ("Garamani Jhapa", "NEPAL CHOWK, HARCHANA SCHOOL, DADA", "Jhapa", 250),
    ("Baniyani Jhapa", "", "Jhapa", 250),
    ("Jhapa Bazar Jhapa", "", "Jhapa", 275),
    ("Shivagunj Jhapa", "", "Jhapa", 275),
    ("Sharanmati Jhapa", "", "Jhapa", 275),
    ("Jhiljhile Jhapa", "", "Jhapa", 275),
    ("Khudunabari Jhapa", "", "Jhapa", 250),
    ("Fikkal Ilam", "", "Ilam", 250),
    ("Illam Ilam", "", "Ilam", 250),
    ("Mangalbare Illam", "MANGALBARE BAZAR, PAIREVANJYANG CHOWK, GAGREVANJYANG", "Ilam", 275),
    ("Nepaltar Illam", "", "Ilam", 250),
    ("Pashupatinagar Ilam", "", "Ilam", 275),
    ("Shree Antu Ilam", "", "Ilam", 275),
    ("Phidim Panchthar", "", "Panchthar", 250),
    ("Jorpokhari Panchthar", "", "Panchthar", 275),
    ("Basantapur Terhathum", "CHITRE, TUTE, DEURALI GUMBA, DANDA KHARKA (3-4 days)", "Terhathum", 325),
    ("Jirikhimti Terhathum", "", "Terhathum", 325),
    ("Myanglungbazar Terhathum", "", "Terhathum", 325),
    ("Taplejung Bazar", "", "Taplejung", 325),
    ("Tumlingtar Sankhuwasabha", "", "Sankhuwasabha", 325),
    ("Chainpur Sankhuwasabha", "", "Sankhuwasabha", 325),
    ("Khandbari Sankhuwasabha", "", "Sankhuwasabha", 325),
    ("Bhojpur Bhojpur", "", "Bhojpur", 300),
    ("Dingla Bhojpur", "", "Bhojpur", 325),
    ("Diktel Khotang", "", "Khotang", 325),
    ("Okhaldhunga Bazar", "", "Okhaldhunga", 325),
    ("Salleri Solu Solukhumbu", "", "Solukhumbu", 325),
    ("Tingla Solu", "", "Solukhumbu", 340),
    ("Lukla Solukhumbu", "LUKLA BAZAR, MUSE, SURKE, CHAURIKHARKA, GHAt, TOKTOK, THAKDIN, BANKAR (delivery time depend on weather 4-6 days)", "Solukhumbu", 300),
    ("Singati Dolakha", "", "Dolakha", 300),
    ("Charikot Dolakha", "", "Dolakha", 250),
    ("Jiri Dolakha", "", "Dolakha", 275),
    ("Mainapokhari Dolakha", "", "Dolakha", 300),
    # Kavrepalanchowk / Sindhupalchok / Nuwakot / Makawanpur / Dhading / Rasuwa
    ("Banepa Kavrepalanchowk", "", "Kavrepalanchowk", 200),
    ("Dhulikhel Kavrepalanchowk", "", "Kavrepalanchowk", 200),
    ("Panchkhal Kavre", "", "Kavrepalanchowk", 250),
    ("Bhakunde Besi Kavre", "", "Kavrepalanchowk", 250),
    ("Dolalghat Kavre", "", "Kavrepalanchowk", 275),
    ("Panauti Kavre", "", "Kavrepalanchowk", 200),
    ("Melamchi Sindhupalchok", "", "Sindhupalchok", 275),
    ("Chautara Sindhupalchok", "", "Sindhupalchok", 275),
    ("Bahrabise Sindhupalchok", "", "Sindhupalchok", 275),
    ("Trishuli Nuwakot", "", "Nuwakot", 250),
    ("Battar Bazar Nuwakot", "", "Nuwakot", 250),
    ("Bidur Nuwakot", "", "Nuwakot", 250),
    ("Hetauda Makawanpur", "", "Makawanpur", 225),
    ("Manahari Makawanpur", "", "Makawanpur", 275),
    ("Bastipur Makawanpur", "", "Makawanpur", 250),
    ("Daman Makawanpur", "", "Makawanpur", 275),
    ("Padam Pokhari Makawanpur", "", "Makawanpur", 250),
    ("Dhading Besi", "", "Dhading", 250),
    ("Malekhu Dhading", "", "Dhading", 250),
    ("Naubise Dhading", "", "Dhading", 275),
    ("Galchi Dhading", "", "Dhading", 275),
    ("Gajuri Dhading", "", "Dhading", 275),
    ("Dhunche Rasuwa", "", "Rasuwa", 300),
    # Misc without clear district
    ("bhidetar", "", "", 275),
    ("Danda Bazar", "", "", 275),
]


class Command(BaseCommand):
    help = 'Seed delivery locations (idempotent)'

    def handle(self, *args, **options):
        created = 0
        skipped = 0
        for name, coverage, district, charge in DELIVERY_LOCATIONS:
            if name.lower().strip() in SKIP_NAMES:
                skipped += 1
                continue
            _, was_created = DeliveryLocation.objects.get_or_create(
                name=name,
                defaults={'coverage': coverage, 'district': district, 'charge': charge},
            )
            if was_created:
                created += 1
        self.stdout.write(
            self.style.SUCCESS(
                f'Done. {created} locations created, {skipped} skipped, '
                f'{len(DELIVERY_LOCATIONS) - created - skipped} already existed.'
            )
        )
